import { ImageSourcePropType } from 'react-native';

export const specificIngredientImages: { [key: string]: ImageSourcePropType } = {
  'acorn squash': require('../assets/pantry/acorn_squash.png'),
  'almond': require('../assets/pantry/almond.png'),
  'amaranth': require('../assets/pantry/amaranth.png'),
  'anchovy': require('../assets/pantry/anchovy.png'),
  'antipasto': require('../assets/pantry/antipasto.png'),
  'apple': require('../assets/pantry/apple.png'),
  'apple pie': require('../assets/pantry/apple_pie.png'),
  'apple sauce': require('../assets/pantry/apple_sauce.png'),
  'apricot': require('../assets/pantry/apricot.png'),
  'artichoke': require('../assets/pantry/artichoke.png'),
  'arugula': require('../assets/pantry/arugula.png'),
  'asparagus': require('../assets/pantry/asparagus.png'),
  'aspic': require('../assets/pantry/aspic.png'),
  'avocado': require('../assets/pantry/avocado.png'),
  'baby back ribs': require('../assets/pantry/baby_back_ribs.png'),
  'bacon': require('../assets/pantry/bacon.png'),
  'bagel': require('../assets/pantry/bagel.png'),
  'baguette': require('../assets/pantry/baguette.png'),
  'baked alaska': require('../assets/pantry/baked_alaska.png'),
  'baklava': require('../assets/pantry/baklava.png'),
  'bamboo shoots': require('../assets/pantry/bamboo_shoots.png'),
  'banana': require('../assets/pantry/banana.png'),
  'barley': require('../assets/pantry/barley.png'),
  'basil': require('../assets/pantry/basil.png'),
  'bass': require('../assets/pantry/bass.png'),
  'bay leaf': require('../assets/pantry/bay_leaf.png'),
  'beancurd': require('../assets/pantry/beancurd.png'),
  'beans': require('../assets/pantry/beans.png'),
  'beef': require('../assets/pantry/beef.png'),
  'beef carpaccio': require('../assets/pantry/beef_carpaccio.png'),
  'beef steak': require('../assets/pantry/beef_steak.png'),
  'beef tartare': require('../assets/pantry/beef_tartare.png'),
  'beet': require('../assets/pantry/beet.png'),
  'beet salad': require('../assets/pantry/beet_salad.png'),
  'beignets': require('../assets/pantry/beignets.png'),
  'bell pepper': require('../assets/pantry/bell_pepper.png'),
  'berry': require('../assets/pantry/berry.png'),
  'bibimbap': require('../assets/pantry/bibimbap.png'),
  'bilberry': require('../assets/pantry/bilberry.png'),
  'birthday cake': require('../assets/pantry/birthday_cake.png'),
  'biscuits': require('../assets/pantry/biscuits.png'),
  'bitter melon': require('../assets/pantry/bitter_melon.png'),
  'black beans': require('../assets/pantry/black_beans.png'),
  'black currant': require('../assets/pantry/black_currant.png'),
  'blackberry': require('../assets/pantry/blackberry.png'),
  'blood orange': require('../assets/pantry/blood_orange.png'),
  'blood sausage': require('../assets/pantry/blood_sausage.png'),
  'blue cheese': require('../assets/pantry/blue_cheese.png'),
  'blueberry': require('../assets/pantry/blueberry.png'),
  'blueberry pie': require('../assets/pantry/blueberry_pie.png'),
  'bok choy': require('../assets/pantry/bok_choy.png'),
  'bonbon': require('../assets/pantry/bonbon.png'),
  'boysenberry': require('../assets/pantry/boysenberry.png'),
  'bread': require('../assets/pantry/bread.png'),
  'bread pudding': require('../assets/pantry/bread_pudding.png'),
  'bread rolls': require('../assets/pantry/bread_rolls.png'),
  'breadfruit': require('../assets/pantry/breadfruit.png'),
  'breadstick': require('../assets/pantry/breadstick.png'),
  'bream': require('../assets/pantry/bream.png'),
  'brie': require('../assets/pantry/brie.png'),
  'brioche': require('../assets/pantry/brioche.png'),
  'brisket': require('../assets/pantry/brisket.png'),
  'brittle': require('../assets/pantry/brittle.png'),
  'broad beans': require('../assets/pantry/broad_beans.png'),
  'broccoli': require('../assets/pantry/broccoli.png'),
  'broccolini': require('../assets/pantry/broccolini.png'),
  'brown rice': require('../assets/pantry/brown_rice.png'),
  'brownie': require('../assets/pantry/brownie.png'),
  'bruschetta': require('../assets/pantry/bruschetta.png'),
  'brussels sprout': require('../assets/pantry/brussels_sprout.png'),
  'buckwheat': require('../assets/pantry/buckwheat.png'),
  'burrito': require('../assets/pantry/burrito.png'),
  'butter': require('../assets/pantry/butter.png'),
  'cabbage': require('../assets/pantry/cabbage.png'),
  'caesar salad': require('../assets/pantry/caesar_salad.png'),
  'cake': require('../assets/pantry/cake.png'),
  'cake pop': require('../assets/pantry/cake_pop.png'),
  'calamari': require('../assets/pantry/calamari.png'),
  'camembert': require('../assets/pantry/camembert.png'),
  'canape': require('../assets/pantry/canape.png'),
  'candy': require('../assets/pantry/candy.png'),
  'candy apple': require('../assets/pantry/candy_apple.png'),
  'candy bar': require('../assets/pantry/candy_bar.png'),
  'cannoli': require('../assets/pantry/cannoli.png'),
  'cantaloupe': require('../assets/pantry/cantaloupe.png'),
  'caper': require('../assets/pantry/caper.png'),
  'caprese salad': require('../assets/pantry/caprese_salad.png'),
  'caramel apple': require('../assets/pantry/caramel_apple.png'),
  'cardoon': require('../assets/pantry/cardoon.png'),
  'carp': require('../assets/pantry/carp.png'),
  'carpaccio': require('../assets/pantry/carpaccio.png'),
  'carrot': require('../assets/pantry/carrot.png'),
  'carrot cake': require('../assets/pantry/carrot_cake.png'),
  'cashew': require('../assets/pantry/cashew.png'),
  'cassava': require('../assets/pantry/cassava.png'),
  'casserole': require('../assets/pantry/casserole.png'),
  'cauliflower': require('../assets/pantry/cauliflower.png'),
  'caviar': require('../assets/pantry/caviar.png'),
  'celery': require('../assets/pantry/celery.png'),
  'cereal': require('../assets/pantry/cereal.png'),
  'ceviche': require('../assets/pantry/ceviche.png'),
  'chard': require('../assets/pantry/chard.png'),
  'cheddar': require('../assets/pantry/cheddar.png'),
  'cheese': require('../assets/pantry/cheese.png'),
  'cheeseburger': require('../assets/pantry/cheeseburger.png'),
  'cheesecake': require('../assets/pantry/cheesecake.png'),
  'cherry': require('../assets/pantry/cherry.png'),
  'cherry tomato': require('../assets/pantry/cherry_tomato.png'),
  'chestnut': require('../assets/pantry/chestnut.png'),
  'chicken': require('../assets/pantry/chicken.png'),
  'chicken breast': require('../assets/pantry/chicken_breast.png'),
  'chicken curry': require('../assets/pantry/chicken_curry.png'),
  'chicken leg': require('../assets/pantry/chicken_leg.png'),
  'chicken wings': require('../assets/pantry/chicken_wings.png'),
  'chickpeas': require('../assets/pantry/chickpeas.png'),
  'chili': require('../assets/pantry/chili.png'),
  'chili pepper': require('../assets/pantry/chili_pepper.png'),
  'chips': require('../assets/pantry/chips.png'),
  'chives': require('../assets/pantry/chives.png'),
  'chocolate': require('../assets/pantry/chocolate.png'),
  'chorizo': require('../assets/pantry/chorizo.png'),
  'chowder': require('../assets/pantry/chowder.png'),
  'churros': require('../assets/pantry/churros.png'),
  'chutney': require('../assets/pantry/chutney.png'),
  'ciabatta': require('../assets/pantry/ciabatta.png'),
  'cinnamon roll': require('../assets/pantry/cinnamon_roll.png'),
  'citron': require('../assets/pantry/citron.png'),
  'citrus': require('../assets/pantry/citrus.png'),
  'clam': require('../assets/pantry/clam.png'),
  'clam chowder': require('../assets/pantry/clam_chowder.png'),
  'clementine': require('../assets/pantry/clementine.png'),
  'cobbler': require('../assets/pantry/cobbler.png'),
  'cockle': require('../assets/pantry/cockle.png'),
  'coconut': require('../assets/pantry/coconut.png'),
  'coleslaw': require('../assets/pantry/coleslaw.png'),
  'collards': require('../assets/pantry/collards.png'),
  'common bean': require('../assets/pantry/common_bean.png'),
  'compote': require('../assets/pantry/compote.png'),
  'cookie': require('../assets/pantry/cookie.png'),
  'corn': require('../assets/pantry/corn.png'),
  'corn bread': require('../assets/pantry/corn_bread.png'),
  'corn salad': require('../assets/pantry/corn_salad.png'),
  'corned beef': require('../assets/pantry/corned_beef.png'),
  'cornflakes': require('../assets/pantry/cornflakes.png'),
  'cottage cheese': require('../assets/pantry/cottage_cheese.png'),
  'couscous': require('../assets/pantry/couscous.png'),
  'crab': require('../assets/pantry/crab.png'),
  'crab cakes': require('../assets/pantry/crab_cakes.png'),
  'cracker': require('../assets/pantry/cracker.png'),
  'cranberry': require('../assets/pantry/cranberry.png'),
  'crayfish': require('../assets/pantry/crayfish.png'),
  'creme brulee': require('../assets/pantry/creme_brulee.png'),
  'crepe': require('../assets/pantry/crepe.png'),
  'crescent roll': require('../assets/pantry/crescent_roll.png'),
  'cress': require('../assets/pantry/cress.png'),
  'crispbread': require('../assets/pantry/crispbread.png'),
  'croissant': require('../assets/pantry/croissant.png'),
  'croque madame': require('../assets/pantry/croque_madame.png'),
  'croquette': require('../assets/pantry/croquette.png'),
  'crouton': require('../assets/pantry/crouton.png'),
  'crunch': require('../assets/pantry/crunch.png'),
  'default': require('../assets/pantry/crunch.png'), // random image as placeholder for defualts
};




export const getAssetForIngredient = (ingredientName: string): ImageSourcePropType => {
  const key = ingredientName.toLowerCase();
  
  if (specificIngredientImages[key]) {
    return specificIngredientImages[key];
  }
  
  return specificIngredientImages['default'];
};